-- AI Smart Finance Tracker -- Supabase schema
--
-- Run this once in the Supabase dashboard: SQL Editor > New query > Run.
-- Then put your project URL and anon key in client/local.properties:
--
--   supabase.url=https://YOUR-PROJECT-REF.supabase.co
--   supabase.anonKey=YOUR-ANON-PUBLIC-KEY

create table if not exists public.expenses (
    id          bigint generated by default as identity primary key,
    user_id     uuid        not null default auth.uid() references auth.users (id) on delete cascade,
    merchant    text        not null,
    amount      numeric(12, 2) not null check (amount >= 0),
    category    text        not null default 'Uncategorized',
    occurred_at timestamptz not null default now(),
    is_anomaly  boolean     not null default false,

    -- Room's local row id. Unique per user so the app can upsert the same
    -- transaction repeatedly without creating duplicates.
    client_id   integer     not null,

    created_at  timestamptz not null default now(),

    constraint expenses_user_client_unique unique (user_id, client_id)
);

create index if not exists expenses_user_occurred_idx
    on public.expenses (user_id, occurred_at desc);

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- This is what makes shipping the anon key in the app safe: the key only
-- identifies the project, and every statement below is scoped to auth.uid(),
-- so a signed-in user can never read or write another user's rows.
-- ---------------------------------------------------------------------------
alter table public.expenses enable row level security;

drop policy if exists "read own expenses"   on public.expenses;
drop policy if exists "insert own expenses" on public.expenses;
drop policy if exists "update own expenses" on public.expenses;
drop policy if exists "delete own expenses" on public.expenses;

create policy "read own expenses"
    on public.expenses for select
    using (auth.uid() = user_id);

create policy "insert own expenses"
    on public.expenses for insert
    with check (auth.uid() = user_id);

create policy "update own expenses"
    on public.expenses for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "delete own expenses"
    on public.expenses for delete
    using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Optional: budgets, if you later want limits to follow the user across devices.
-- The app currently keeps budgets in Room only.
-- ---------------------------------------------------------------------------
create table if not exists public.budgets (
    user_id       uuid           not null default auth.uid() references auth.users (id) on delete cascade,
    category      text           not null,
    monthly_limit numeric(12, 2) not null check (monthly_limit > 0),
    updated_at    timestamptz    not null default now(),
    primary key (user_id, category)
);

alter table public.budgets enable row level security;

drop policy if exists "manage own budgets" on public.budgets;

create policy "manage own budgets"
    on public.budgets for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
